# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jabac\OneDrive - Universidad del Norte\Documentos\Tareas\Proyecto final\Scripts\Repositorio\Proyecto-Final\UI\InterfaceGrid.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 677)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imgs/iconBus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(191, 191, 191)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GridSimulationTab = QtWidgets.QTabWidget(self.centralwidget)
        self.GridSimulationTab.setGeometry(QtCore.QRect(10, 10, 941, 521))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.GridSimulationTab.setFont(font)
        self.GridSimulationTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.GridSimulationTab.setStyleSheet("background-color: rgb(191, 191, 191);\n"
"gridline-color: rgb(0, 0, 0);")
        self.GridSimulationTab.setObjectName("GridSimulationTab")
        self.LoadPropertiesTab = QtWidgets.QWidget()
        self.LoadPropertiesTab.setObjectName("LoadPropertiesTab")
        self.PowerFlowButton = QtWidgets.QPushButton(self.LoadPropertiesTab)
        self.PowerFlowButton.setGeometry(QtCore.QRect(180, 300, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.PowerFlowButton.setFont(font)
        self.PowerFlowButton.setToolTip("")
        self.PowerFlowButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.PowerFlowButton.setObjectName("PowerFlowButton")
        self.ChargingComboBox = QtWidgets.QComboBox(self.LoadPropertiesTab)
        self.ChargingComboBox.setGeometry(QtCore.QRect(150, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ChargingComboBox.setFont(font)
        self.ChargingComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChargingComboBox.setObjectName("ChargingComboBox")
        self.ChargingComboBox.addItem("")
        self.ChargingComboBox.addItem("")
        self.NodeLabel = QtWidgets.QLabel(self.LoadPropertiesTab)
        self.NodeLabel.setGeometry(QtCore.QRect(540, 360, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NodeLabel.setFont(font)
        self.NodeLabel.setObjectName("NodeLabel")
        self.NodeListComboBox = QtWidgets.QComboBox(self.LoadPropertiesTab)
        self.NodeListComboBox.setGeometry(QtCore.QRect(590, 360, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NodeListComboBox.setFont(font)
        self.NodeListComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NodeListComboBox.setObjectName("NodeListComboBox")
        self.NodeLocationButton = QtWidgets.QPushButton(self.LoadPropertiesTab)
        self.NodeLocationButton.setGeometry(QtCore.QRect(760, 360, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.NodeLocationButton.setFont(font)
        self.NodeLocationButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.NodeLocationButton.setObjectName("NodeLocationButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.LoadPropertiesTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(540, 110, 341, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.AssignmentLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.AssignmentLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.AssignmentLayout.setContentsMargins(0, 0, 0, 0)
        self.AssignmentLayout.setObjectName("AssignmentLayout")
        self.FondoAssignment = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.FondoAssignment.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FondoAssignment.setText("")
        self.FondoAssignment.setObjectName("FondoAssignment")
        self.AssignmentLayout.addWidget(self.FondoAssignment)
        self.ChargerLabel = QtWidgets.QLabel(self.LoadPropertiesTab)
        self.ChargerLabel.setGeometry(QtCore.QRect(580, 70, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ChargerLabel.setFont(font)
        self.ChargerLabel.setAutoFillBackground(False)
        self.ChargerLabel.setObjectName("ChargerLabel")
        self.LoadChargersNodesButton = QtWidgets.QPushButton(self.LoadPropertiesTab)
        self.LoadChargersNodesButton.setGeometry(QtCore.QRect(540, 310, 221, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.LoadChargersNodesButton.setFont(font)
        self.LoadChargersNodesButton.setAutoFillBackground(False)
        self.LoadChargersNodesButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.LoadChargersNodesButton.setObjectName("LoadChargersNodesButton")
        self.SaveButton = QtWidgets.QPushButton(self.LoadPropertiesTab)
        self.SaveButton.setGeometry(QtCore.QRect(770, 310, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.SaveButton.setFont(font)
        self.SaveButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.SaveButton.setObjectName("SaveButton")
        self.DssFileLineFrame = QtWidgets.QFrame(self.LoadPropertiesTab)
        self.DssFileLineFrame.setEnabled(False)
        self.DssFileLineFrame.setGeometry(QtCore.QRect(120, 160, 251, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.DssFileLineFrame.setPalette(palette)
        self.DssFileLineFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DssFileLineFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DssFileLineFrame.setObjectName("DssFileLineFrame")
        self.DssFileLine = QtWidgets.QLineEdit(self.DssFileLineFrame)
        self.DssFileLine.setGeometry(QtCore.QRect(10, 0, 231, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DssFileLine.setFont(font)
        self.DssFileLine.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.DssFileLine.setObjectName("DssFileLine")
        self.SearchFileButton = QtWidgets.QPushButton(self.LoadPropertiesTab)
        self.SearchFileButton.setEnabled(True)
        self.SearchFileButton.setGeometry(QtCore.QRect(200, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.SearchFileButton.setFont(font)
        self.SearchFileButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.SearchFileButton.setObjectName("SearchFileButton")
        self.GridSimulationTab.addTab(self.LoadPropertiesTab, "")
        self.ResultsTab = QtWidgets.QWidget()
        self.ResultsTab.setObjectName("ResultsTab")
        self.VoltageProfileButton = QtWidgets.QPushButton(self.ResultsTab)
        self.VoltageProfileButton.setGeometry(QtCore.QRect(280, 410, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VoltageProfileButton.setFont(font)
        self.VoltageProfileButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.VoltageProfileButton.setObjectName("VoltageProfileButton")
        self.SummaryButton = QtWidgets.QPushButton(self.ResultsTab)
        self.SummaryButton.setGeometry(QtCore.QRect(120, 410, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.SummaryButton.setFont(font)
        self.SummaryButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.SummaryButton.setObjectName("SummaryButton")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.ResultsTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(120, 40, 351, 351))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.SummaryLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.SummaryLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.SummaryLayout.setContentsMargins(0, 0, 0, 0)
        self.SummaryLayout.setObjectName("SummaryLayout")
        self.FondoAssignment_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.FondoAssignment_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FondoAssignment_2.setText("")
        self.FondoAssignment_2.setObjectName("FondoAssignment_2")
        self.SummaryLayout.addWidget(self.FondoAssignment_2)
        self.NodeListComboBoxVoltages = QtWidgets.QComboBox(self.ResultsTab)
        self.NodeListComboBoxVoltages.setGeometry(QtCore.QRect(600, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NodeListComboBoxVoltages.setFont(font)
        self.NodeListComboBoxVoltages.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NodeListComboBoxVoltages.setObjectName("NodeListComboBoxVoltages")
        self.LineListComboBox = QtWidgets.QComboBox(self.ResultsTab)
        self.LineListComboBox.setGeometry(QtCore.QRect(600, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LineListComboBox.setFont(font)
        self.LineListComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LineListComboBox.setObjectName("LineListComboBox")
        self.VoltagesGraphButton = QtWidgets.QPushButton(self.ResultsTab)
        self.VoltagesGraphButton.setGeometry(QtCore.QRect(770, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.VoltagesGraphButton.setFont(font)
        self.VoltagesGraphButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.VoltagesGraphButton.setObjectName("VoltagesGraphButton")
        self.NodeLabelVoltages = QtWidgets.QLabel(self.ResultsTab)
        self.NodeLabelVoltages.setGeometry(QtCore.QRect(550, 160, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.NodeLabelVoltages.setFont(font)
        self.NodeLabelVoltages.setObjectName("NodeLabelVoltages")
        self.LineLabel = QtWidgets.QLabel(self.ResultsTab)
        self.LineLabel.setGeometry(QtCore.QRect(550, 320, 51, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LineLabel.setFont(font)
        self.LineLabel.setObjectName("LineLabel")
        self.VoltageLabel = QtWidgets.QLabel(self.ResultsTab)
        self.VoltageLabel.setGeometry(QtCore.QRect(640, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VoltageLabel.setFont(font)
        self.VoltageLabel.setAutoFillBackground(False)
        self.VoltageLabel.setObjectName("VoltageLabel")
        self.CurrentLabel = QtWidgets.QLabel(self.ResultsTab)
        self.CurrentLabel.setGeometry(QtCore.QRect(640, 270, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentLabel.setFont(font)
        self.CurrentLabel.setAutoFillBackground(False)
        self.CurrentLabel.setObjectName("CurrentLabel")
        self.CurrentsGraphButton = QtWidgets.QPushButton(self.ResultsTab)
        self.CurrentsGraphButton.setGeometry(QtCore.QRect(770, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentsGraphButton.setFont(font)
        self.CurrentsGraphButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.CurrentsGraphButton.setObjectName("CurrentsGraphButton")
        self.GridSimulationTab.addTab(self.ResultsTab, "")
        self.VoltagesTab = QtWidgets.QWidget()
        self.VoltagesTab.setObjectName("VoltagesTab")
        self.GridSimulationTab.addTab(self.VoltagesTab, "")
        self.ButtonsFrame = QtWidgets.QFrame(self.centralwidget)
        self.ButtonsFrame.setGeometry(QtCore.QRect(20, 540, 921, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.ButtonsFrame.setPalette(palette)
        self.ButtonsFrame.setAutoFillBackground(False)
        self.ButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ButtonsFrame.setLineWidth(2)
        self.ButtonsFrame.setObjectName("ButtonsFrame")
        self.RouteButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.RouteButton.setEnabled(True)
        self.RouteButton.setGeometry(QtCore.QRect(30, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RouteButton.setFont(font)
        self.RouteButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.RouteButton.setObjectName("RouteButton")
        self.BusButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.BusButton.setGeometry(QtCore.QRect(220, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BusButton.setFont(font)
        self.BusButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.BusButton.setObjectName("BusButton")
        self.DynamicButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.DynamicButton.setGeometry(QtCore.QRect(600, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicButton.setFont(font)
        self.DynamicButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.DynamicButton.setObjectName("DynamicButton")
        self.OpportunityButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.OpportunityButton.setGeometry(QtCore.QRect(410, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityButton.setFont(font)
        self.OpportunityButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.OpportunityButton.setObjectName("OpportunityButton")
        self.GridButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.GridButton.setEnabled(False)
        self.GridButton.setGeometry(QtCore.QRect(790, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GridButton.setFont(font)
        self.GridButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.GridButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.GridButton.setObjectName("GridButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 26))
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("background-color: rgb(191, 191, 191)")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUser_Manual = QtWidgets.QAction(MainWindow)
        self.actionUser_Manual.setObjectName("actionUser_Manual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.GridSimulationTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electric Bus Recharging Analyzer - Grid Impact"))
        self.PowerFlowButton.setStatusTip(_translate("MainWindow", "Push to run Power flow"))
        self.PowerFlowButton.setText(_translate("MainWindow", "Power Flow"))
        self.ChargingComboBox.setStatusTip(_translate("MainWindow", "Choose the charging technology that prefer analyze"))
        self.ChargingComboBox.setItemText(0, _translate("MainWindow", "Opportunity Charging"))
        self.ChargingComboBox.setItemText(1, _translate("MainWindow", "In Motion Charging"))
        self.NodeLabel.setText(_translate("MainWindow", "Node"))
        self.NodeListComboBox.setStatusTip(_translate("MainWindow", "Choose the node that prefer see"))
        self.NodeLocationButton.setStatusTip(_translate("MainWindow", "Push to see the Node Location"))
        self.NodeLocationButton.setText(_translate("MainWindow", "Node Location"))
        self.ChargerLabel.setText(_translate("MainWindow", "Charger Node Asignment"))
        self.LoadChargersNodesButton.setStatusTip(_translate("MainWindow", "Push to Load Chargers and Nodes"))
        self.LoadChargersNodesButton.setText(_translate("MainWindow", "Load Chargers and Nodes"))
        self.SaveButton.setStatusTip(_translate("MainWindow", "Push to Save choices"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.DssFileLineFrame.setAccessibleName(_translate("MainWindow", ".csv"))
        self.SearchFileButton.setStatusTip(_translate("MainWindow", "Push to Search Dss File "))
        self.SearchFileButton.setText(_translate("MainWindow", "Search\n"
"File"))
        self.GridSimulationTab.setTabText(self.GridSimulationTab.indexOf(self.LoadPropertiesTab), _translate("MainWindow", "Load Properties"))
        self.VoltageProfileButton.setStatusTip(_translate("MainWindow", "Push to see the Voltage Profile"))
        self.VoltageProfileButton.setText(_translate("MainWindow", "Voltage Profile"))
        self.SummaryButton.setStatusTip(_translate("MainWindow", "Push to see the Summary"))
        self.SummaryButton.setText(_translate("MainWindow", "Summary"))
        self.NodeListComboBoxVoltages.setStatusTip(_translate("MainWindow", "Choose the node that prefer see"))
        self.LineListComboBox.setStatusTip(_translate("MainWindow", "Choose the node that prefer see"))
        self.VoltagesGraphButton.setStatusTip(_translate("MainWindow", "Push to graph the simulation"))
        self.VoltagesGraphButton.setText(_translate("MainWindow", "Graph"))
        self.NodeLabelVoltages.setText(_translate("MainWindow", "Node"))
        self.LineLabel.setText(_translate("MainWindow", "Line"))
        self.VoltageLabel.setText(_translate("MainWindow", "Voltages Behavior"))
        self.CurrentLabel.setText(_translate("MainWindow", "Currents Behavior"))
        self.CurrentsGraphButton.setStatusTip(_translate("MainWindow", "Push to graph the simulation"))
        self.CurrentsGraphButton.setText(_translate("MainWindow", "Graph"))
        self.GridSimulationTab.setTabText(self.GridSimulationTab.indexOf(self.ResultsTab), _translate("MainWindow", "Results"))
        self.GridSimulationTab.setTabText(self.GridSimulationTab.indexOf(self.VoltagesTab), _translate("MainWindow", "Voltages and currents"))
        self.RouteButton.setStatusTip(_translate("MainWindow", "Push to go to the Route tab"))
        self.RouteButton.setText(_translate("MainWindow", "Route"))
        self.BusButton.setStatusTip(_translate("MainWindow", "Push to go to the Bus Parameters tab"))
        self.BusButton.setText(_translate("MainWindow", "Bus\n"
"Parameters"))
        self.DynamicButton.setStatusTip(_translate("MainWindow", "Push to go to the In Motion Charging tab"))
        self.DynamicButton.setText(_translate("MainWindow", "In Motion\n"
"Charging"))
        self.OpportunityButton.setStatusTip(_translate("MainWindow", "Push to go to the Opportunity Charging tab"))
        self.OpportunityButton.setText(_translate("MainWindow", "Opportunity\n"
"Charging"))
        self.GridButton.setStatusTip(_translate("MainWindow", "Push to go to the Grid tab"))
        self.GridButton.setText(_translate("MainWindow", "Grid\n"
"Impact"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

