# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jabac\OneDrive - Universidad del Norte\Documentos\Tareas\Proyecto final\Scripts\Repositorio\Proyecto-Final\UI\InterfaceOpportunity.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 686)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imgs/iconBus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonsFrame = QtWidgets.QFrame(self.centralwidget)
        self.ButtonsFrame.setGeometry(QtCore.QRect(20, 540, 921, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.ButtonsFrame.setPalette(palette)
        self.ButtonsFrame.setAutoFillBackground(False)
        self.ButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ButtonsFrame.setLineWidth(2)
        self.ButtonsFrame.setObjectName("ButtonsFrame")
        self.RouteButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.RouteButton.setEnabled(True)
        self.RouteButton.setGeometry(QtCore.QRect(30, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RouteButton.setFont(font)
        self.RouteButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.RouteButton.setObjectName("RouteButton")
        self.BusButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.BusButton.setGeometry(QtCore.QRect(220, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BusButton.setFont(font)
        self.BusButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.BusButton.setObjectName("BusButton")
        self.DynamicButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.DynamicButton.setGeometry(QtCore.QRect(600, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicButton.setFont(font)
        self.DynamicButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.DynamicButton.setObjectName("DynamicButton")
        self.OpportunityButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.OpportunityButton.setEnabled(False)
        self.OpportunityButton.setGeometry(QtCore.QRect(410, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityButton.setFont(font)
        self.OpportunityButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.OpportunityButton.setObjectName("OpportunityButton")
        self.GridButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.GridButton.setGeometry(QtCore.QRect(790, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GridButton.setFont(font)
        self.GridButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.GridButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.GridButton.setObjectName("GridButton")
        self.SimulationOpportunityTab = QtWidgets.QTabWidget(self.centralwidget)
        self.SimulationOpportunityTab.setGeometry(QtCore.QRect(10, 10, 941, 521))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.SimulationOpportunityTab.setFont(font)
        self.SimulationOpportunityTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SimulationOpportunityTab.setStyleSheet("background-color: rgb(191, 191, 191);\n"
"gridline-color: rgb(0, 0, 0);")
        self.SimulationOpportunityTab.setObjectName("SimulationOpportunityTab")
        self.ParametersOpportunityTab = QtWidgets.QWidget()
        self.ParametersOpportunityTab.setObjectName("ParametersOpportunityTab")
        self.ChargingParameterLabel = QtWidgets.QLabel(self.ParametersOpportunityTab)
        self.ChargingParameterLabel.setGeometry(QtCore.QRect(170, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ChargingParameterLabel.setFont(font)
        self.ChargingParameterLabel.setObjectName("ChargingParameterLabel")
        self.OppChargingParametersTable = QtWidgets.QTableWidget(self.ParametersOpportunityTab)
        self.OppChargingParametersTable.setGeometry(QtCore.QRect(110, 110, 371, 291))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.OppChargingParametersTable.setFont(font)
        self.OppChargingParametersTable.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.OppChargingParametersTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OppChargingParametersTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.OppChargingParametersTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.OppChargingParametersTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.OppChargingParametersTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.OppChargingParametersTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.OppChargingParametersTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.OppChargingParametersTable.setObjectName("OppChargingParametersTable")
        self.OppChargingParametersTable.setColumnCount(1)
        self.OppChargingParametersTable.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.OppChargingParametersTable.setItem(6, 0, item)
        self.OppChargingParametersTable.horizontalHeader().setStretchLastSection(False)
        self.OppChargingParametersTable.verticalHeader().setStretchLastSection(False)
        self.RefreshSectionsButton = QtWidgets.QPushButton(self.ParametersOpportunityTab)
        self.RefreshSectionsButton.setGeometry(QtCore.QRect(550, 370, 121, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RefreshSectionsButton.setFont(font)
        self.RefreshSectionsButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.RefreshSectionsButton.setObjectName("RefreshSectionsButton")
        self.ChargeSectionsLabel = QtWidgets.QLabel(self.ParametersOpportunityTab)
        self.ChargeSectionsLabel.setGeometry(QtCore.QRect(620, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ChargeSectionsLabel.setFont(font)
        self.ChargeSectionsLabel.setObjectName("ChargeSectionsLabel")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.ParametersOpportunityTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(580, 80, 241, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.StopslLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.StopslLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.StopslLayout.setContentsMargins(0, 0, 0, 0)
        self.StopslLayout.setObjectName("StopslLayout")
        self.Fondo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Fondo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Fondo.setText("")
        self.Fondo.setObjectName("Fondo")
        self.StopslLayout.addWidget(self.Fondo)
        self.SaveSectionsButton = QtWidgets.QPushButton(self.ParametersOpportunityTab)
        self.SaveSectionsButton.setGeometry(QtCore.QRect(730, 370, 121, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SaveSectionsButton.setFont(font)
        self.SaveSectionsButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.SaveSectionsButton.setObjectName("SaveSectionsButton")
        self.SimulationOpportunityTab.addTab(self.ParametersOpportunityTab, "")
        self.OperationDiagramTab = QtWidgets.QWidget()
        self.OperationDiagramTab.setObjectName("OperationDiagramTab")
        self.OpportunityLoadSimButton = QtWidgets.QPushButton(self.OperationDiagramTab)
        self.OpportunityLoadSimButton.setGeometry(QtCore.QRect(340, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityLoadSimButton.setFont(font)
        self.OpportunityLoadSimButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.OpportunityLoadSimButton.setObjectName("OpportunityLoadSimButton")
        self.OpportunityprogressBar = QtWidgets.QProgressBar(self.OperationDiagramTab)
        self.OpportunityprogressBar.setGeometry(QtCore.QRect(380, 50, 181, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityprogressBar.setFont(font)
        self.OpportunityprogressBar.setAutoFillBackground(False)
        self.OpportunityprogressBar.setStyleSheet("")
        self.OpportunityprogressBar.setProperty("value", 0)
        self.OpportunityprogressBar.setTextVisible(True)
        self.OpportunityprogressBar.setOrientation(QtCore.Qt.Horizontal)
        self.OpportunityprogressBar.setInvertedAppearance(False)
        self.OpportunityprogressBar.setObjectName("OpportunityprogressBar")
        self.OpportunityCurveWidget = QtWidgets.QWidget(self.OperationDiagramTab)
        self.OpportunityCurveWidget.setGeometry(QtCore.QRect(20, 80, 901, 311))
        self.OpportunityCurveWidget.setObjectName("OpportunityCurveWidget")
        self.ElementscomboBox = QtWidgets.QComboBox(self.OperationDiagramTab)
        self.ElementscomboBox.setGeometry(QtCore.QRect(180, 400, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.ElementscomboBox.setFont(font)
        self.ElementscomboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ElementscomboBox.setObjectName("ElementscomboBox")
        self.ElementscomboBox.addItem("")
        self.ElementscomboBox.addItem("")
        self.VariablescomboBox = QtWidgets.QComboBox(self.OperationDiagramTab)
        self.VariablescomboBox.setGeometry(QtCore.QRect(180, 450, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.VariablescomboBox.setFont(font)
        self.VariablescomboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VariablescomboBox.setObjectName("VariablescomboBox")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.OpportunityGraphButton = QtWidgets.QPushButton(self.OperationDiagramTab)
        self.OpportunityGraphButton.setGeometry(QtCore.QRect(600, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityGraphButton.setFont(font)
        self.OpportunityGraphButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.OpportunityGraphButton.setObjectName("OpportunityGraphButton")
        self.ElementLabel = QtWidgets.QLabel(self.OperationDiagramTab)
        self.ElementLabel.setGeometry(QtCore.QRect(70, 410, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ElementLabel.setFont(font)
        self.ElementLabel.setObjectName("ElementLabel")
        self.VariableLabel = QtWidgets.QLabel(self.OperationDiagramTab)
        self.VariableLabel.setGeometry(QtCore.QRect(70, 460, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VariableLabel.setFont(font)
        self.VariableLabel.setObjectName("VariableLabel")
        self.SimulationOpportunityTab.addTab(self.OperationDiagramTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUser_Manual = QtWidgets.QAction(MainWindow)
        self.actionUser_Manual.setObjectName("actionUser_Manual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.SimulationOpportunityTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electric Bus Recharging Analyzer - Opportunity Charging"))
        self.RouteButton.setStatusTip(_translate("MainWindow", "Push to go to the Route tab"))
        self.RouteButton.setText(_translate("MainWindow", "Route"))
        self.BusButton.setStatusTip(_translate("MainWindow", "Push to go to the Bus Parameters tab"))
        self.BusButton.setText(_translate("MainWindow", "Bus\n"
"Parameters"))
        self.DynamicButton.setStatusTip(_translate("MainWindow", "Push to go to the In Motion Charging tab"))
        self.DynamicButton.setText(_translate("MainWindow", "In Motion\n"
"Charging"))
        self.OpportunityButton.setStatusTip(_translate("MainWindow", "Push to go to the Opportunity Charging tab"))
        self.OpportunityButton.setText(_translate("MainWindow", "Opportunity\n"
"Charging"))
        self.GridButton.setStatusTip(_translate("MainWindow", "Push to go to the Grid tab"))
        self.GridButton.setText(_translate("MainWindow", "Grid\n"
"Impact"))
        self.ChargingParameterLabel.setText(_translate("MainWindow", "Charging Parameters"))
        item = self.OppChargingParametersTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "BC [kwh]:Battery capacity per bus"))
        item = self.OppChargingParametersTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "SoCi [%]: Initial charge state"))
        item = self.OppChargingParametersTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "CL: Charge sections"))
        item = self.OppChargingParametersTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "CP [kW]: Charger power"))
        item = self.OppChargingParametersTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "nC [%]: Charging efficiency"))
        item = self.OppChargingParametersTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "IT [s]: Connection time to charging"))
        item = self.OppChargingParametersTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "DT [s]: Disconnection time"))
        item = self.OppChargingParametersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.OppChargingParametersTable.isSortingEnabled()
        self.OppChargingParametersTable.setSortingEnabled(False)
        item = self.OppChargingParametersTable.item(0, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.OppChargingParametersTable.item(1, 0)
        item.setText(_translate("MainWindow", "80"))
        item = self.OppChargingParametersTable.item(2, 0)
        item.setText(_translate("MainWindow", "S8,S18,S1"))
        item = self.OppChargingParametersTable.item(3, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.OppChargingParametersTable.item(4, 0)
        item.setText(_translate("MainWindow", "90"))
        item = self.OppChargingParametersTable.item(5, 0)
        item.setText(_translate("MainWindow", "8"))
        item = self.OppChargingParametersTable.item(6, 0)
        item.setText(_translate("MainWindow", "4"))
        self.OppChargingParametersTable.setSortingEnabled(__sortingEnabled)
        self.RefreshSectionsButton.setStatusTip(_translate("MainWindow", "Push to go load charge sections"))
        self.RefreshSectionsButton.setText(_translate("MainWindow", "Load Charge\n"
"Sections"))
        self.ChargeSectionsLabel.setText(_translate("MainWindow", "CL: Charge Sections"))
        self.SaveSectionsButton.setStatusTip(_translate("MainWindow", "Push to go load charge sections"))
        self.SaveSectionsButton.setText(_translate("MainWindow", "Save Charge\n"
"Sections"))
        self.SimulationOpportunityTab.setTabText(self.SimulationOpportunityTab.indexOf(self.ParametersOpportunityTab), _translate("MainWindow", "Parameters"))
        self.OpportunityLoadSimButton.setStatusTip(_translate("MainWindow", "Push to load the simulation"))
        self.OpportunityLoadSimButton.setText(_translate("MainWindow", "Load simulation"))
        self.ElementscomboBox.setStatusTip(_translate("MainWindow", "Choose the element that prefer analyze"))
        self.ElementscomboBox.setItemText(0, _translate("MainWindow", "Bus"))
        self.ElementscomboBox.setItemText(1, _translate("MainWindow", "Charger"))
        self.VariablescomboBox.setStatusTip(_translate("MainWindow", "Choose the variable prefer to graph"))
        self.VariablescomboBox.setItemText(0, _translate("MainWindow", "Energy"))
        self.VariablescomboBox.setItemText(1, _translate("MainWindow", "Power"))
        self.VariablescomboBox.setItemText(2, _translate("MainWindow", "Slope"))
        self.VariablescomboBox.setItemText(3, _translate("MainWindow", "(SoC) State of Charge"))
        self.VariablescomboBox.setItemText(4, _translate("MainWindow", "Chargers"))
        self.VariablescomboBox.setItemText(5, _translate("MainWindow", "Charger vector"))
        self.OpportunityGraphButton.setStatusTip(_translate("MainWindow", "Push to load the simulation"))
        self.OpportunityGraphButton.setText(_translate("MainWindow", "Graph"))
        self.ElementLabel.setText(_translate("MainWindow", "Element"))
        self.VariableLabel.setText(_translate("MainWindow", "Variable"))
        self.SimulationOpportunityTab.setTabText(self.SimulationOpportunityTab.indexOf(self.OperationDiagramTab), _translate("MainWindow", "Simulation"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual"))
        self.actionUser_Manual.setStatusTip(_translate("MainWindow", "Go to the User Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "Show the About window"))

