# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jabac\OneDrive - Universidad del Norte\Documentos\Tareas\Proyecto final\Scripts\Repositorio\Proyecto-Final\UI\InterfaceDynamic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 686)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imgs/iconBus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonsFrame = QtWidgets.QFrame(self.centralwidget)
        self.ButtonsFrame.setGeometry(QtCore.QRect(20, 540, 921, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.ButtonsFrame.setPalette(palette)
        self.ButtonsFrame.setAutoFillBackground(False)
        self.ButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ButtonsFrame.setLineWidth(2)
        self.ButtonsFrame.setObjectName("ButtonsFrame")
        self.RouteButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.RouteButton.setGeometry(QtCore.QRect(30, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RouteButton.setFont(font)
        self.RouteButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.RouteButton.setObjectName("RouteButton")
        self.BusButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.BusButton.setEnabled(True)
        self.BusButton.setGeometry(QtCore.QRect(220, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BusButton.setFont(font)
        self.BusButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.BusButton.setObjectName("BusButton")
        self.DynamicButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.DynamicButton.setEnabled(False)
        self.DynamicButton.setGeometry(QtCore.QRect(600, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicButton.setFont(font)
        self.DynamicButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.DynamicButton.setObjectName("DynamicButton")
        self.OpportunityButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.OpportunityButton.setGeometry(QtCore.QRect(410, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityButton.setFont(font)
        self.OpportunityButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.OpportunityButton.setObjectName("OpportunityButton")
        self.GridButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.GridButton.setGeometry(QtCore.QRect(790, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GridButton.setFont(font)
        self.GridButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.GridButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.GridButton.setObjectName("GridButton")
        self.FleetParametersTable = QtWidgets.QTableWidget(self.centralwidget)
        self.FleetParametersTable.setGeometry(QtCore.QRect(290, 120, 371, 281))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FleetParametersTable.setFont(font)
        self.FleetParametersTable.setStyleSheet("")
        self.FleetParametersTable.setObjectName("FleetParametersTable")
        self.FleetParametersTable.setColumnCount(1)
        self.FleetParametersTable.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(6, 0, item)
        self.SimulationDynamicTab = QtWidgets.QTabWidget(self.centralwidget)
        self.SimulationDynamicTab.setGeometry(QtCore.QRect(10, 10, 941, 521))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.SimulationDynamicTab.setFont(font)
        self.SimulationDynamicTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SimulationDynamicTab.setStyleSheet("background-color: rgb(191, 191, 191);\n"
"gridline-color: rgb(0, 0, 0);")
        self.SimulationDynamicTab.setObjectName("SimulationDynamicTab")
        self.ParametersDynamicTab = QtWidgets.QWidget()
        self.ParametersDynamicTab.setObjectName("ParametersDynamicTab")
        self.ChargingParameterLabel = QtWidgets.QLabel(self.ParametersDynamicTab)
        self.ChargingParameterLabel.setGeometry(QtCore.QRect(170, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ChargingParameterLabel.setFont(font)
        self.ChargingParameterLabel.setObjectName("ChargingParameterLabel")
        self.ImcChargingParametersTable = QtWidgets.QTableWidget(self.ParametersDynamicTab)
        self.ImcChargingParametersTable.setGeometry(QtCore.QRect(110, 110, 371, 291))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ImcChargingParametersTable.setFont(font)
        self.ImcChargingParametersTable.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.ImcChargingParametersTable.setObjectName("ImcChargingParametersTable")
        self.ImcChargingParametersTable.setColumnCount(1)
        self.ImcChargingParametersTable.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.ImcChargingParametersTable.setItem(6, 0, item)
        self.RefreshSectionsButton = QtWidgets.QPushButton(self.ParametersDynamicTab)
        self.RefreshSectionsButton.setGeometry(QtCore.QRect(640, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RefreshSectionsButton.setFont(font)
        self.RefreshSectionsButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.RefreshSectionsButton.setObjectName("RefreshSectionsButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.ParametersDynamicTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(579, 110, 241, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.StopslLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.StopslLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.StopslLayout.setContentsMargins(0, 0, 0, 0)
        self.StopslLayout.setObjectName("StopslLayout")
        self.Fondo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Fondo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Fondo.setText("")
        self.Fondo.setObjectName("Fondo")
        self.StopslLayout.addWidget(self.Fondo)
        self.SimulationDynamicTab.addTab(self.ParametersDynamicTab, "")
        self.OperationDiagramTab = QtWidgets.QWidget()
        self.OperationDiagramTab.setObjectName("OperationDiagramTab")
        self.DynamicLoadSimButton = QtWidgets.QPushButton(self.OperationDiagramTab)
        self.DynamicLoadSimButton.setGeometry(QtCore.QRect(340, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicLoadSimButton.setFont(font)
        self.DynamicLoadSimButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.DynamicLoadSimButton.setObjectName("DynamicLoadSimButton")
        self.DynamicprogressBar = QtWidgets.QProgressBar(self.OperationDiagramTab)
        self.DynamicprogressBar.setGeometry(QtCore.QRect(380, 50, 181, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicprogressBar.setFont(font)
        self.DynamicprogressBar.setAutoFillBackground(False)
        self.DynamicprogressBar.setStyleSheet("")
        self.DynamicprogressBar.setProperty("value", 0)
        self.DynamicprogressBar.setTextVisible(True)
        self.DynamicprogressBar.setOrientation(QtCore.Qt.Horizontal)
        self.DynamicprogressBar.setInvertedAppearance(False)
        self.DynamicprogressBar.setObjectName("DynamicprogressBar")
        self.DynamicCurveWidget = QtWidgets.QWidget(self.OperationDiagramTab)
        self.DynamicCurveWidget.setGeometry(QtCore.QRect(20, 90, 901, 311))
        self.DynamicCurveWidget.setObjectName("DynamicCurveWidget")
        self.ElementscomboBox = QtWidgets.QComboBox(self.OperationDiagramTab)
        self.ElementscomboBox.setGeometry(QtCore.QRect(180, 400, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.ElementscomboBox.setFont(font)
        self.ElementscomboBox.setObjectName("ElementscomboBox")
        self.ElementscomboBox.addItem("")
        self.ElementscomboBox.addItem("")
        self.VariablescomboBox = QtWidgets.QComboBox(self.OperationDiagramTab)
        self.VariablescomboBox.setGeometry(QtCore.QRect(180, 450, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.VariablescomboBox.setFont(font)
        self.VariablescomboBox.setObjectName("VariablescomboBox")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.VariablescomboBox.addItem("")
        self.DynamicGraphButton = QtWidgets.QPushButton(self.OperationDiagramTab)
        self.DynamicGraphButton.setGeometry(QtCore.QRect(600, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicGraphButton.setFont(font)
        self.DynamicGraphButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.DynamicGraphButton.setObjectName("DynamicGraphButton")
        self.ElementLabel = QtWidgets.QLabel(self.OperationDiagramTab)
        self.ElementLabel.setGeometry(QtCore.QRect(70, 410, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ElementLabel.setFont(font)
        self.ElementLabel.setObjectName("ElementLabel")
        self.VariableLabel = QtWidgets.QLabel(self.OperationDiagramTab)
        self.VariableLabel.setGeometry(QtCore.QRect(70, 460, 101, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VariableLabel.setFont(font)
        self.VariableLabel.setObjectName("VariableLabel")
        self.SimulationDynamicTab.addTab(self.OperationDiagramTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.statusbar.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUser_Manual = QtWidgets.QAction(MainWindow)
        self.actionUser_Manual.setObjectName("actionUser_Manual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.SimulationDynamicTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electric Bus Recharging Analyzer - In Motion Charging"))
        self.RouteButton.setStatusTip(_translate("MainWindow", "Push to go to the Route tab"))
        self.RouteButton.setText(_translate("MainWindow", "Route"))
        self.BusButton.setStatusTip(_translate("MainWindow", "Push to go to the Bus Parameters tab"))
        self.BusButton.setText(_translate("MainWindow", "Bus\n"
"Parameters"))
        self.DynamicButton.setStatusTip(_translate("MainWindow", "Push to go to the In Motion Charging tab"))
        self.DynamicButton.setText(_translate("MainWindow", "In Motion\n"
"Charging"))
        self.OpportunityButton.setStatusTip(_translate("MainWindow", "Push to go to the Opportunity Charging tab"))
        self.OpportunityButton.setText(_translate("MainWindow", "Opportunity\n"
"Charging"))
        self.GridButton.setStatusTip(_translate("MainWindow", "Push to go to the Grid tab"))
        self.GridButton.setText(_translate("MainWindow", "Grid\n"
"Impact"))
        item = self.FleetParametersTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "BC [kwh]:Battery capacity per bus"))
        item = self.FleetParametersTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "SoCi [%]: Initial charge state"))
        item = self.FleetParametersTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "CL: Charge sections"))
        item = self.FleetParametersTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "CP [kW]: Charger power"))
        item = self.FleetParametersTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "nC [%]: Charging efficiency"))
        item = self.FleetParametersTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "IT [s]: Connection time to recharge"))
        item = self.FleetParametersTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "DT [s]: Disconnection time"))
        item = self.FleetParametersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.FleetParametersTable.isSortingEnabled()
        self.FleetParametersTable.setSortingEnabled(False)
        item = self.FleetParametersTable.item(0, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.FleetParametersTable.item(1, 0)
        item.setText(_translate("MainWindow", "80"))
        item = self.FleetParametersTable.item(2, 0)
        item.setText(_translate("MainWindow", "P8,P18,P1"))
        item = self.FleetParametersTable.item(3, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.FleetParametersTable.item(4, 0)
        item.setText(_translate("MainWindow", "90"))
        item = self.FleetParametersTable.item(5, 0)
        item.setText(_translate("MainWindow", "8"))
        item = self.FleetParametersTable.item(6, 0)
        item.setText(_translate("MainWindow", "4"))
        self.FleetParametersTable.setSortingEnabled(__sortingEnabled)
        self.ChargingParameterLabel.setText(_translate("MainWindow", "Charging Parameters"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "BC [kwh]:Battery capacity per bus"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "SoCi [%]: Initial charge state"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "CL: Charge sections"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "CP [kW]: Charger power"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "nC [%]: Charging efficiency"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "IT [s]: Connection time to charging"))
        item = self.ImcChargingParametersTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "DT [s]: Disconnection time"))
        item = self.ImcChargingParametersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.ImcChargingParametersTable.isSortingEnabled()
        self.ImcChargingParametersTable.setSortingEnabled(False)
        item = self.ImcChargingParametersTable.item(0, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.ImcChargingParametersTable.item(1, 0)
        item.setText(_translate("MainWindow", "80"))
        item = self.ImcChargingParametersTable.item(2, 0)
        item.setText(_translate("MainWindow", "S8,S18,S1"))
        item = self.ImcChargingParametersTable.item(3, 0)
        item.setText(_translate("MainWindow", "250"))
        item = self.ImcChargingParametersTable.item(4, 0)
        item.setText(_translate("MainWindow", "90"))
        item = self.ImcChargingParametersTable.item(5, 0)
        item.setText(_translate("MainWindow", "8"))
        item = self.ImcChargingParametersTable.item(6, 0)
        item.setText(_translate("MainWindow", "4"))
        self.ImcChargingParametersTable.setSortingEnabled(__sortingEnabled)
        self.RefreshSectionsButton.setStatusTip(_translate("MainWindow", "Push to go to the Route tab"))
        self.RefreshSectionsButton.setText(_translate("MainWindow", "Load Charge\n"
"Sections"))
        self.SimulationDynamicTab.setTabText(self.SimulationDynamicTab.indexOf(self.ParametersDynamicTab), _translate("MainWindow", "Parameters"))
        self.DynamicLoadSimButton.setStatusTip(_translate("MainWindow", "Push to load the simulation"))
        self.DynamicLoadSimButton.setText(_translate("MainWindow", "Load simulation"))
        self.ElementscomboBox.setStatusTip(_translate("MainWindow", "Choose the element that prefer analyze"))
        self.ElementscomboBox.setItemText(0, _translate("MainWindow", "Bus"))
        self.ElementscomboBox.setItemText(1, _translate("MainWindow", "Charger"))
        self.VariablescomboBox.setStatusTip(_translate("MainWindow", "Choose the variable prefer to graph"))
        self.VariablescomboBox.setItemText(0, _translate("MainWindow", "Energy"))
        self.VariablescomboBox.setItemText(1, _translate("MainWindow", "Power"))
        self.VariablescomboBox.setItemText(2, _translate("MainWindow", "Slope"))
        self.VariablescomboBox.setItemText(3, _translate("MainWindow", "(SoC) State of Charge"))
        self.VariablescomboBox.setItemText(4, _translate("MainWindow", "Chargers"))
        self.VariablescomboBox.setItemText(5, _translate("MainWindow", "Charger vector"))
        self.DynamicGraphButton.setStatusTip(_translate("MainWindow", "Push to load the simulation"))
        self.DynamicGraphButton.setText(_translate("MainWindow", "Graph"))
        self.ElementLabel.setText(_translate("MainWindow", "Element"))
        self.VariableLabel.setText(_translate("MainWindow", "Variable"))
        self.SimulationDynamicTab.setTabText(self.SimulationDynamicTab.indexOf(self.OperationDiagramTab), _translate("MainWindow", "Simulation"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual"))
        self.actionUser_Manual.setStatusTip(_translate("MainWindow", "Go to the User Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "Show the About window "))

