# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jabac\OneDrive - Universidad del Norte\Documentos\Tareas\Proyecto final\Scripts\Repositorio\Proyecto-Final\UI\InterfaceBus.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 677)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 223, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(95, 95, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imgs/iconBus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonsFrame = QtWidgets.QFrame(self.centralwidget)
        self.ButtonsFrame.setGeometry(QtCore.QRect(20, 540, 921, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.ButtonsFrame.setPalette(palette)
        self.ButtonsFrame.setAutoFillBackground(False)
        self.ButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ButtonsFrame.setLineWidth(2)
        self.ButtonsFrame.setObjectName("ButtonsFrame")
        self.RouteButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.RouteButton.setGeometry(QtCore.QRect(30, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RouteButton.setFont(font)
        self.RouteButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.RouteButton.setObjectName("RouteButton")
        self.BusButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.BusButton.setEnabled(False)
        self.BusButton.setGeometry(QtCore.QRect(220, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BusButton.setFont(font)
        self.BusButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.BusButton.setObjectName("BusButton")
        self.DynamicButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.DynamicButton.setGeometry(QtCore.QRect(600, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DynamicButton.setFont(font)
        self.DynamicButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.DynamicButton.setObjectName("DynamicButton")
        self.OpportunityButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.OpportunityButton.setGeometry(QtCore.QRect(410, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OpportunityButton.setFont(font)
        self.OpportunityButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.OpportunityButton.setObjectName("OpportunityButton")
        self.GridButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.GridButton.setGeometry(QtCore.QRect(790, 10, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GridButton.setFont(font)
        self.GridButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.GridButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.GridButton.setObjectName("GridButton")
        self.BusParametersTab = QtWidgets.QTabWidget(self.centralwidget)
        self.BusParametersTab.setGeometry(QtCore.QRect(10, 10, 941, 521))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.BusParametersTab.setFont(font)
        self.BusParametersTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.BusParametersTab.setStyleSheet("background-color: rgb(191, 191, 191);\n"
"gridline-color: rgb(0, 0, 0);")
        self.BusParametersTab.setObjectName("BusParametersTab")
        self.BusGeneralDataTab = QtWidgets.QWidget()
        self.BusGeneralDataTab.setStyleSheet("")
        self.BusGeneralDataTab.setObjectName("BusGeneralDataTab")
        self.BusParametersTable = QtWidgets.QTableWidget(self.BusGeneralDataTab)
        self.BusParametersTable.setGeometry(QtCore.QRect(40, 60, 361, 161))
        self.BusParametersTable.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.BusParametersTable.setObjectName("BusParametersTable")
        self.BusParametersTable.setColumnCount(1)
        self.BusParametersTable.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.BusParametersTable.setItem(8, 0, item)
        self.SpeedCurveTable = QtWidgets.QTableWidget(self.BusGeneralDataTab)
        self.SpeedCurveTable.setGeometry(QtCore.QRect(80, 300, 271, 131))
        self.SpeedCurveTable.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.SpeedCurveTable.setObjectName("SpeedCurveTable")
        self.SpeedCurveTable.setColumnCount(1)
        self.SpeedCurveTable.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SpeedCurveTable.setItem(2, 0, item)
        self.BusParameterLabel = QtWidgets.QLabel(self.BusGeneralDataTab)
        self.BusParameterLabel.setGeometry(QtCore.QRect(140, 20, 151, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BusParameterLabel.setFont(font)
        self.BusParameterLabel.setObjectName("BusParameterLabel")
        self.SpeedCurveLabel = QtWidgets.QLabel(self.BusGeneralDataTab)
        self.SpeedCurveLabel.setGeometry(QtCore.QRect(160, 270, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SpeedCurveLabel.setFont(font)
        self.SpeedCurveLabel.setObjectName("SpeedCurveLabel")
        self.PlotBusGenDataButton = QtWidgets.QPushButton(self.BusGeneralDataTab)
        self.PlotBusGenDataButton.setGeometry(QtCore.QRect(610, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PlotBusGenDataButton.setFont(font)
        self.PlotBusGenDataButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.PlotBusGenDataButton.setObjectName("PlotBusGenDataButton")
        self.BusGenDataFrame = QtWidgets.QFrame(self.BusGeneralDataTab)
        self.BusGenDataFrame.setGeometry(QtCore.QRect(430, 60, 491, 421))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.BusGenDataFrame.setPalette(palette)
        self.BusGenDataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BusGenDataFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BusGenDataFrame.setObjectName("BusGenDataFrame")
        self.SpeedCurveWidget = QtWidgets.QWidget(self.BusGenDataFrame)
        self.SpeedCurveWidget.setGeometry(QtCore.QRect(9, 10, 471, 201))
        self.SpeedCurveWidget.setObjectName("SpeedCurveWidget")
        self.DistanceCurveWidget = QtWidgets.QWidget(self.BusGenDataFrame)
        self.DistanceCurveWidget.setGeometry(QtCore.QRect(10, 210, 471, 201))
        self.DistanceCurveWidget.setObjectName("DistanceCurveWidget")
        self.BusParametersTab.addTab(self.BusGeneralDataTab, "")
        self.BusFleetDataTab = QtWidgets.QWidget()
        self.BusFleetDataTab.setObjectName("BusFleetDataTab")
        self.FleetParameterLabel = QtWidgets.QLabel(self.BusFleetDataTab)
        self.FleetParameterLabel.setGeometry(QtCore.QRect(190, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FleetParameterLabel.setFont(font)
        self.FleetParameterLabel.setObjectName("FleetParameterLabel")
        self.FleetParametersTable = QtWidgets.QTableWidget(self.BusFleetDataTab)
        self.FleetParametersTable.setGeometry(QtCore.QRect(70, 110, 421, 321))
        self.FleetParametersTable.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.FleetParametersTable.setObjectName("FleetParametersTable")
        self.FleetParametersTable.setColumnCount(1)
        self.FleetParametersTable.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.FleetParametersTable.setItem(7, 0, item)
        self.TimeParametersgroupBox = QtWidgets.QGroupBox(self.BusFleetDataTab)
        self.TimeParametersgroupBox.setGeometry(QtCore.QRect(590, 60, 291, 341))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TimeParametersgroupBox.setFont(font)
        self.TimeParametersgroupBox.setObjectName("TimeParametersgroupBox")
        self.PeakTimesToolBox = QtWidgets.QToolBox(self.TimeParametersgroupBox)
        self.PeakTimesToolBox.setGeometry(QtCore.QRect(50, 50, 191, 141))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PeakTimesToolBox.setFont(font)
        self.PeakTimesToolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PeakTimesToolBox.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.PeakTimesToolBox.setObjectName("PeakTimesToolBox")
        self.PeakTimes1Page = QtWidgets.QWidget()
        self.PeakTimes1Page.setGeometry(QtCore.QRect(0, 0, 191, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PeakTimes1Page.setFont(font)
        self.PeakTimes1Page.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PeakTimes1Page.setObjectName("PeakTimes1Page")
        self.STPtimeEdit = QtWidgets.QTimeEdit(self.PeakTimes1Page)
        self.STPtimeEdit.setGeometry(QtCore.QRect(10, 0, 118, 22))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.STPtimeEdit.setFont(font)
        self.STPtimeEdit.setAutoFillBackground(False)
        self.STPtimeEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.STPtimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(6, 0, 0)))
        self.STPtimeEdit.setTime(QtCore.QTime(6, 0, 0))
        self.STPtimeEdit.setObjectName("STPtimeEdit")
        self.ETPtimeEdit = QtWidgets.QTimeEdit(self.PeakTimes1Page)
        self.ETPtimeEdit.setGeometry(QtCore.QRect(10, 30, 118, 22))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.ETPtimeEdit.setFont(font)
        self.ETPtimeEdit.setAutoFillBackground(False)
        self.ETPtimeEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.ETPtimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(8, 0, 0)))
        self.ETPtimeEdit.setTime(QtCore.QTime(8, 0, 0))
        self.ETPtimeEdit.setObjectName("ETPtimeEdit")
        self.STPlabel = QtWidgets.QLabel(self.PeakTimes1Page)
        self.STPlabel.setGeometry(QtCore.QRect(140, 0, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.STPlabel.setFont(font)
        self.STPlabel.setObjectName("STPlabel")
        self.ETPlabel = QtWidgets.QLabel(self.PeakTimes1Page)
        self.ETPlabel.setGeometry(QtCore.QRect(140, 30, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.ETPlabel.setFont(font)
        self.ETPlabel.setObjectName("ETPlabel")
        self.PeakTimesToolBox.addItem(self.PeakTimes1Page, "")
        self.PeakTimes2Page = QtWidgets.QWidget()
        self.PeakTimes2Page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.PeakTimes2Page.setObjectName("PeakTimes2Page")
        self.STMPtimeEdit = QtWidgets.QTimeEdit(self.PeakTimes2Page)
        self.STMPtimeEdit.setGeometry(QtCore.QRect(10, 0, 118, 22))
        self.STMPtimeEdit.setAutoFillBackground(False)
        self.STMPtimeEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.STMPtimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(15, 30, 0)))
        self.STMPtimeEdit.setTime(QtCore.QTime(15, 30, 0))
        self.STMPtimeEdit.setObjectName("STMPtimeEdit")
        self.STMPlabel = QtWidgets.QLabel(self.PeakTimes2Page)
        self.STMPlabel.setGeometry(QtCore.QRect(140, 0, 41, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.STMPlabel.setFont(font)
        self.STMPlabel.setObjectName("STMPlabel")
        self.EMPtimeEdit = QtWidgets.QTimeEdit(self.PeakTimes2Page)
        self.EMPtimeEdit.setGeometry(QtCore.QRect(10, 30, 118, 22))
        self.EMPtimeEdit.setAutoFillBackground(False)
        self.EMPtimeEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.EMPtimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(17, 0, 0)))
        self.EMPtimeEdit.setTime(QtCore.QTime(17, 0, 0))
        self.EMPtimeEdit.setObjectName("EMPtimeEdit")
        self.EMPlabel = QtWidgets.QLabel(self.PeakTimes2Page)
        self.EMPlabel.setGeometry(QtCore.QRect(140, 30, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.EMPlabel.setFont(font)
        self.EMPlabel.setObjectName("EMPlabel")
        self.PeakTimesToolBox.addItem(self.PeakTimes2Page, "")
        self.StartEndTimesToolBox = QtWidgets.QToolBox(self.TimeParametersgroupBox)
        self.StartEndTimesToolBox.setGeometry(QtCore.QRect(50, 200, 191, 101))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StartEndTimesToolBox.setFont(font)
        self.StartEndTimesToolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartEndTimesToolBox.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.StartEndTimesToolBox.setObjectName("StartEndTimesToolBox")
        self.StartEndTimesPage = QtWidgets.QWidget()
        self.StartEndTimesPage.setGeometry(QtCore.QRect(0, 0, 191, 66))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StartEndTimesPage.setFont(font)
        self.StartEndTimesPage.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.StartEndTimesPage.setObjectName("StartEndTimesPage")
        self.STFtimeEdit = QtWidgets.QTimeEdit(self.StartEndTimesPage)
        self.STFtimeEdit.setGeometry(QtCore.QRect(10, 0, 118, 22))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.STFtimeEdit.setFont(font)
        self.STFtimeEdit.setAutoFillBackground(False)
        self.STFtimeEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.STFtimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(5, 0, 0)))
        self.STFtimeEdit.setTime(QtCore.QTime(5, 0, 0))
        self.STFtimeEdit.setObjectName("STFtimeEdit")
        self.ETFtimeEdit = QtWidgets.QTimeEdit(self.StartEndTimesPage)
        self.ETFtimeEdit.setGeometry(QtCore.QRect(10, 30, 118, 22))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.ETFtimeEdit.setFont(font)
        self.ETFtimeEdit.setAutoFillBackground(False)
        self.ETFtimeEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.ETFtimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(9, 30, 0)))
        self.ETFtimeEdit.setTime(QtCore.QTime(9, 30, 0))
        self.ETFtimeEdit.setObjectName("ETFtimeEdit")
        self.STFlabel = QtWidgets.QLabel(self.StartEndTimesPage)
        self.STFlabel.setGeometry(QtCore.QRect(140, 0, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.STFlabel.setFont(font)
        self.STFlabel.setObjectName("STFlabel")
        self.ETFlabel = QtWidgets.QLabel(self.StartEndTimesPage)
        self.ETFlabel.setGeometry(QtCore.QRect(140, 30, 31, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.ETFlabel.setFont(font)
        self.ETFlabel.setObjectName("ETFlabel")
        self.StartEndTimesToolBox.addItem(self.StartEndTimesPage, "")
        self.BusParametersTab.addTab(self.BusFleetDataTab, "")
        self.OperationDiagramTab = QtWidgets.QWidget()
        self.OperationDiagramTab.setObjectName("OperationDiagramTab")
        self.GenOperationDiagramButton = QtWidgets.QPushButton(self.OperationDiagramTab)
        self.GenOperationDiagramButton.setGeometry(QtCore.QRect(340, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GenOperationDiagramButton.setFont(font)
        self.GenOperationDiagramButton.setStyleSheet("background-color: rgb(159, 159, 159);")
        self.GenOperationDiagramButton.setObjectName("GenOperationDiagramButton")
        self.BusprogressBar = QtWidgets.QProgressBar(self.OperationDiagramTab)
        self.BusprogressBar.setGeometry(QtCore.QRect(380, 50, 181, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BusprogressBar.setFont(font)
        self.BusprogressBar.setAutoFillBackground(False)
        self.BusprogressBar.setStyleSheet("")
        self.BusprogressBar.setProperty("value", 0)
        self.BusprogressBar.setTextVisible(True)
        self.BusprogressBar.setOrientation(QtCore.Qt.Horizontal)
        self.BusprogressBar.setInvertedAppearance(False)
        self.BusprogressBar.setObjectName("BusprogressBar")
        self.PositionSpeedtabWidget = QtWidgets.QTabWidget(self.OperationDiagramTab)
        self.PositionSpeedtabWidget.setGeometry(QtCore.QRect(10, 80, 921, 401))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PositionSpeedtabWidget.setFont(font)
        self.PositionSpeedtabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.PositionSpeedtabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.PositionSpeedtabWidget.setObjectName("PositionSpeedtabWidget")
        self.PositionTab = QtWidgets.QWidget()
        self.PositionTab.setObjectName("PositionTab")
        self.OPPositionCurveWidget = QtWidgets.QWidget(self.PositionTab)
        self.OPPositionCurveWidget.setGeometry(QtCore.QRect(20, 20, 851, 361))
        self.OPPositionCurveWidget.setObjectName("OPPositionCurveWidget")
        self.PositionSpeedtabWidget.addTab(self.PositionTab, "")
        self.SpeedTab = QtWidgets.QWidget()
        self.SpeedTab.setObjectName("SpeedTab")
        self.OPSpeedCurveWidget = QtWidgets.QWidget(self.SpeedTab)
        self.OPSpeedCurveWidget.setGeometry(QtCore.QRect(20, 20, 851, 361))
        self.OPSpeedCurveWidget.setObjectName("OPSpeedCurveWidget")
        self.PositionSpeedtabWidget.addTab(self.SpeedTab, "")
        self.BusParametersTab.addTab(self.OperationDiagramTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUser_Manual = QtWidgets.QAction(MainWindow)
        self.actionUser_Manual.setObjectName("actionUser_Manual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionUser_Manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.BusParametersTab.setCurrentIndex(0)
        self.PeakTimesToolBox.setCurrentIndex(0)
        self.StartEndTimesToolBox.setCurrentIndex(0)
        self.PositionSpeedtabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Electric Bus Recharging Analyzer - Bus Parameters"))
        self.RouteButton.setStatusTip(_translate("MainWindow", "Push to go to the Route tab"))
        self.RouteButton.setText(_translate("MainWindow", "Route"))
        self.BusButton.setStatusTip(_translate("MainWindow", "Push to go to the Bus Parameters tab"))
        self.BusButton.setText(_translate("MainWindow", "Bus\n"
"Parameters"))
        self.DynamicButton.setStatusTip(_translate("MainWindow", "Push to go to the In Motion Charging tab"))
        self.DynamicButton.setText(_translate("MainWindow", "In Motion\n"
"Charging"))
        self.OpportunityButton.setStatusTip(_translate("MainWindow", "Push to go to the Opportunity Charging tab"))
        self.OpportunityButton.setText(_translate("MainWindow", "Opportunity\n"
"Charging"))
        self.GridButton.setStatusTip(_translate("MainWindow", "Push to go to the Grid tab"))
        self.GridButton.setText(_translate("MainWindow", "Grid\n"
"Impact"))
        item = self.BusParametersTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "fr: Rolling friction coefficient"))
        item = self.BusParametersTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "m [kg]: Total vehicle mass"))
        item = self.BusParametersTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "g [m/s2]: Gravity acceleration"))
        item = self.BusParametersTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "rho [kg/m3]: Air density"))
        item = self.BusParametersTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "alpha: Air resistance coefficient"))
        item = self.BusParametersTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "A [m2]: Front area of the vehicle"))
        item = self.BusParametersTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Paux [kW]: Auxiliary load consumption"))
        item = self.BusParametersTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "nout [%] : Consumption efficiency"))
        item = self.BusParametersTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "nin [%]: Regeneration efficiency"))
        item = self.BusParametersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.BusParametersTable.isSortingEnabled()
        self.BusParametersTable.setSortingEnabled(False)
        item = self.BusParametersTable.item(0, 0)
        item.setText(_translate("MainWindow", "0.02"))
        item = self.BusParametersTable.item(1, 0)
        item.setText(_translate("MainWindow", "15900"))
        item = self.BusParametersTable.item(2, 0)
        item.setText(_translate("MainWindow", "9.81"))
        item = self.BusParametersTable.item(3, 0)
        item.setText(_translate("MainWindow", "1.29"))
        item = self.BusParametersTable.item(4, 0)
        item.setText(_translate("MainWindow", "0.66"))
        item = self.BusParametersTable.item(5, 0)
        item.setText(_translate("MainWindow", "8.28"))
        item = self.BusParametersTable.item(6, 0)
        item.setText(_translate("MainWindow", "5.03"))
        item = self.BusParametersTable.item(7, 0)
        item.setText(_translate("MainWindow", "85"))
        item = self.BusParametersTable.item(8, 0)
        item.setText(_translate("MainWindow", "75"))
        self.BusParametersTable.setSortingEnabled(__sortingEnabled)
        item = self.SpeedCurveTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Acceleration [m/s2]:"))
        item = self.SpeedCurveTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Braking [m/s2]"))
        item = self.SpeedCurveTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Maximum speed [km/h]: "))
        item = self.SpeedCurveTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.SpeedCurveTable.isSortingEnabled()
        self.SpeedCurveTable.setSortingEnabled(False)
        item = self.SpeedCurveTable.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.SpeedCurveTable.item(1, 0)
        item.setText(_translate("MainWindow", "1.2"))
        item = self.SpeedCurveTable.item(2, 0)
        item.setText(_translate("MainWindow", "50"))
        self.SpeedCurveTable.setSortingEnabled(__sortingEnabled)
        self.BusParameterLabel.setText(_translate("MainWindow", "Bus Parameters"))
        self.SpeedCurveLabel.setText(_translate("MainWindow", "Speed Curve"))
        self.PlotBusGenDataButton.setStatusTip(_translate("MainWindow", "Push to plot the Speed and Distance Curve"))
        self.PlotBusGenDataButton.setText(_translate("MainWindow", "Plot"))
        self.BusGenDataFrame.setAccessibleName(_translate("MainWindow", ".csv"))
        self.BusParametersTab.setTabText(self.BusParametersTab.indexOf(self.BusGeneralDataTab), _translate("MainWindow", "Bus General Data"))
        self.FleetParameterLabel.setText(_translate("MainWindow", "Fleet Parameters"))
        item = self.FleetParametersTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "NBP: Total number of buses during peak period"))
        item = self.FleetParametersTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "NP: Number of peak periods"))
        item = self.FleetParametersTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "NMP: Number of average peak periods"))
        item = self.FleetParametersTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "FPP [s]: Dispatch frequency during peak period"))
        item = self.FleetParametersTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "ITS [s]: Idle time at each stop "))
        item = self.FleetParametersTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "ITT [s] : Idle time at terminal stop"))
        item = self.FleetParametersTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "NBV: Total number of valley buses"))
        item = self.FleetParametersTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "FPV [s]: Dispatch Frequency during valley period"))
        item = self.FleetParametersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.FleetParametersTable.isSortingEnabled()
        self.FleetParametersTable.setSortingEnabled(False)
        item = self.FleetParametersTable.item(0, 0)
        item.setText(_translate("MainWindow", "7"))
        item = self.FleetParametersTable.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.FleetParametersTable.item(2, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.FleetParametersTable.item(3, 0)
        item.setText(_translate("MainWindow", "120"))
        item = self.FleetParametersTable.item(4, 0)
        item.setText(_translate("MainWindow", "20"))
        item = self.FleetParametersTable.item(5, 0)
        item.setText(_translate("MainWindow", "240"))
        item = self.FleetParametersTable.item(6, 0)
        item.setText(_translate("MainWindow", "6"))
        item = self.FleetParametersTable.item(7, 0)
        item.setText(_translate("MainWindow", "180"))
        self.FleetParametersTable.setSortingEnabled(__sortingEnabled)
        self.TimeParametersgroupBox.setTitle(_translate("MainWindow", "Time parameters"))
        self.STPlabel.setText(_translate("MainWindow", "STP"))
        self.ETPlabel.setText(_translate("MainWindow", "ETP"))
        self.PeakTimesToolBox.setItemText(self.PeakTimesToolBox.indexOf(self.PeakTimes1Page), _translate("MainWindow", "Peak Period 1 "))
        self.STMPlabel.setText(_translate("MainWindow", "STMP"))
        self.EMPlabel.setText(_translate("MainWindow", "EMP"))
        self.PeakTimesToolBox.setItemText(self.PeakTimesToolBox.indexOf(self.PeakTimes2Page), _translate("MainWindow", "Peak Period 2"))
        self.STFlabel.setText(_translate("MainWindow", "STF"))
        self.ETFlabel.setText(_translate("MainWindow", "ETF"))
        self.StartEndTimesToolBox.setItemText(self.StartEndTimesToolBox.indexOf(self.StartEndTimesPage), _translate("MainWindow", "Start and End Times"))
        self.BusParametersTab.setTabText(self.BusParametersTab.indexOf(self.BusFleetDataTab), _translate("MainWindow", "Bus Fleet Data"))
        self.GenOperationDiagramButton.setStatusTip(_translate("MainWindow", "Push to generate the Operation diagram"))
        self.GenOperationDiagramButton.setText(_translate("MainWindow", "Generate Operation Diagram"))
        self.PositionSpeedtabWidget.setTabText(self.PositionSpeedtabWidget.indexOf(self.PositionTab), _translate("MainWindow", "Position"))
        self.PositionSpeedtabWidget.setTabText(self.PositionSpeedtabWidget.indexOf(self.SpeedTab), _translate("MainWindow", "Speed"))
        self.BusParametersTab.setTabText(self.BusParametersTab.indexOf(self.OperationDiagramTab), _translate("MainWindow", "Operation Diagram"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual"))
        self.actionUser_Manual.setStatusTip(_translate("MainWindow", "Go to the User Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "Show the About window"))

