%% Gráficas en pdf 
clear
close all
clc
% File's route
txt_file = 'C:\Users\jabac\OneDrive - Universidad del Norte\Documentos\Tareas\Proyecto final\Scripts\Repositorio\Proyecto-Final\Versión 2022-01\Results\Opp\I3.txt';
% Data table
data_table = readtable(txt_file);
% Diagram dimensions
width = 8.5;    %for a ieee paper
height = 5.3;   %for a ieee paper
% Figure setup
x0=2*2.54;
y0=1*2.54;
f1 = figure('Units','centimeters',...
            'Position',[0 0 width height],...
            'PaperPositionMode','auto');
a = plot(minutes(data_table.Time), data_table.I1,"Color","b");
hold on
b = plot(minutes(data_table.Time), data_table.I2,"Color","r");
c = plot(minutes(data_table.Time), data_table.I3,"Color","g");
grid on
set(gca,'Units','normalized',...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',8,...
'FontName','Times',...
'GridLineStyle',':',...
'GridColor','k',...
'GridAlpha',0.5,...
'xlim',[minutes(0), minutes(1440)])
xtickformat('hh:mm')

leg = legend('$I_1$','$I_2$','$I_3$');
set(leg,'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times',...
'Location','best',...
'Orientation','Vertical',...
'box','off',...
'Interpreter','latex')

ylabel('I [A]',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',8,...
'FontName','Times',...
'Interpreter','latex')

xlabel('Time [h]',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',8,...
'FontName','Times',...
'Interpreter','latex')


set(f1,'PaperUnits','centimeters','PaperSize',[width height]); %set the paper size to what you want  
print(f1,'I3_Opp.pdf','-dpdf') % then print it